server:
    port: 7088
    context-path: /mall
#freemarker
spring:
    freemarker:
        allow-request-override: false
        cache: true
        check-template-location: true
        charset: UTF-8
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: false
        expose-spring-macro-helpers: false
        request-context-attribute: request
        template-loader-path: classpath:/templates/
        suffix: .html
#mysql druid
    datasource:
        name: mall
        url: jdbc:mysql://localhost:3306/mall?characterEncoding=UTF-8
        username: root
        password: 123abc
            # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,log4j
        maxActive: 1000
        initialSize: 500
        maxWait: 60000
        minIdle: 500
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        #cachePrepStmts: true 开启二级缓存
        testOnBorrow: true
        testOnReturn: true
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    #rabbitmq
    rabbitmq:
        host: localhost
        port: 15672
        username: guest
        password: guest
        virtual-host: /
        listener:
            simple:
              concurrency: 10    #消费者数量
              max-concurrency: 10
              prefetch: 1   #一次从队列里取一个
              auto-startup: true
              default-requeue-rejected: true #重新消费
        template:
            retry:
              enabled: true
              initial-interval: 1000
              max-attempts: 3
              max-interval: 10000
              multiplier: 1.0
#mybatis
mybatis:
  type-aliases-package: com.moss.bean
  mapper-locations: classpath:com/moss/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
#redis
redis:
    host: localhost
    port: 6379
    timeout: 3
    password: 123456
    poolMaxTotal: 500
    poolMaxIdle: 200
    poolMaxWait: 200
logging:
  level: debug


