server:
    port: 7088
    context-path: /mall
#freemarker
spring:
    freemarker:
        allow-request-override: false
        cache: true
        check-template-location: true
        charset: UTF-8
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: false
        expose-spring-macro-helpers: false
        request-context-attribute: request
        template-loader-path: classpath:/templates/
        suffix: .html
#mysql druid
    datasource:
        name: mall
        url: jdbc:mysql://localhost:3306/mall?characterEncoding=UTF-8
        username: root
        password: 123abc
            # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,log4j
        maxActive: 50
        initialSize: 5
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        #cachePrepStmts: true 开启二级缓存
        testOnBorrow: true
        testOnReturn: true
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
#mybatis
mybatis:
  type-aliases-package: com.moss.bean
  mapper-locations: classpath:com/moss/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
#redis
redis:
    host: localhost
    port: 6379
    timeout: 3
    password: 123456
    poolMaxTotal: 10
    poolMaxIdle: 10
    poolMaxWait: 3
logging:
  level: debug

